name: Update Star Chart

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  update-star-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install system dependencies for canvas
        run: sudo apt-get update && sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Generate star chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run generate-star-chart

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # 使用 PAT
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add images/star-chart.png
          git commit -m "Update star chart" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/iawooo/ctt.git
          git push
